# Spam Classifier 
1) load libs, and data
2) create a empty corpus
3) loop through messages, regex to remove unwanted symbils, lowercase them, split to remove spaces and form a list
4) stem them and store in the list, finally join to form a trimmed sentence
5) append the sentence to corpus
6) train test split
7) import tfidf
8) fit transform on the test with max features mentioned, and n-grams
9) transform on x_test, this way voacb in test is not leaked in tfidf or cv vectorizer
10) array is ready with bag odf words 
11) Multinomial NB - naive algo ideal for text realted task
12) predict and calculate accuracy, f1, precision etc..

In [5]:
import numpy as np
import pandas as pd
messages = pd.read_csv('SpamClassifier-master/smsspamcollection/SMSSpamCollection',sep='\t',names=["label","message"])

In [7]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [9]:
corpus=[]
for i in range(0,len(messages)):
    review = re.sub('[^a-zA-Z0-9]',' ',messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(x) for x in review if not x in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)
    

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
ti = TfidfVectorizer(max_features=2000,ngram_range=(2,3))

In [11]:
from sklearn.model_selection import train_test_split


In [16]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri 2 wkli comp win fa cup final tkt 21st may 2005 text fa 87121 receiv entri question std txt rate c appli 08452810075over18',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl 3 week word back like fun still tb ok xxx std chg send 1 50 rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press 9 copi friend callertun',
 'winner valu network custom select receivea 900 prize reward claim call 09061701461 claim code kl341 valid 12 hour',
 'mobil 11 month u r entitl updat latest colour mobil camera free call mobil updat co free 08002986030',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash 100 20 000 pound txt csh11 send 87575 cost 150p day 6day 16 tsandc appli repli hl 4 info',
 'urgent 1 week free mem

In [20]:
y=pd.get_dummies(messages['label'])
y=y.iloc[:,0].values
y

array([ True,  True, False, ...,  True,  True,  True])

In [22]:
X_tr,X_test,y_tr,y_test = train_test_split(corpus,y,test_size = 0.25)

In [24]:
X_tr = ti.fit_transform(X_tr).toarray()
X_test = ti.transform(X_test).toarray()

In [26]:
X_tr

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [28]:
X_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [30]:
from sklearn.naive_bayes import MultinomialNB

In [32]:
ti.vocabulary_

{'doubl min': 470,
 'min doubl': 1054,
 'doubl txt': 473,
 'price linerent': 1301,
 'call mobileupd8': 281,
 '08000839402 call2optout': 10,
 'doubl min doubl': 472,
 'min doubl txt': 1055,
 'go got': 697,
 'claim free': 335,
 'free camera': 591,
 'camera phone': 291,
 'offer end': 1199,
 'claim free camera': 336,
 'free camera phone': 592,
 'back home': 209,
 'great weekend': 764,
 'didnt get': 445,
 'hope good': 826,
 'messag sent': 1051,
 'tri get': 1703,
 'run away': 1393,
 'care enough': 297,
 'sunshin quiz': 1615,
 'quiz win': 1325,
 'soni dvd': 1536,
 'best life': 219,
 'gud nyt': 788,
 '2nd time': 66,
 'time tri': 1672,
 'tri contact': 1698,
 'prize claim': 1308,
 'claim easi': 333,
 'easi call': 489,
 '10p per': 32,
 'per minut': 1246,
 'minut bt': 1060,
 'bt nation': 257,
 'nation rate': 1129,
 '2nd time tri': 67,
 'time tri contact': 1673,
 'pound prize claim': 1291,
 'prize claim easi': 1309,
 'claim easi call': 334,
 '10p per minut': 33,
 'per minut bt': 1247,
 'minut bt na

In [34]:
tfidf_pred_model = MultinomialNB().fit(X_tr,y_tr)

In [36]:
y_pred = tfidf_pred_model.predict(X_test)

In [38]:
from sklearn.metrics import accuracy_score, classification_report

In [40]:
accuracy_score(y_pred=y_pred,y_true=y_test)

0.9454414931801867

In [42]:
print(classification_report(y_pred=y_pred,y_true=y_test))

              precision    recall  f1-score   support

       False       0.99      0.58      0.73       180
        True       0.94      1.00      0.97      1213

    accuracy                           0.95      1393
   macro avg       0.97      0.79      0.85      1393
weighted avg       0.95      0.95      0.94      1393

